### ISSUE TITLE
Some minor issues I found in the stylesheet

### ISSUE THREAD

**Issue by dkrutsko** [JorgenVatle/vue-sweetalert-icons#1]
Hello, I found two problems you may want to look into:
1) There's a typo [here]( https://github.com/JorgenVatle/vue-sweetalert-icons/blob/master/src/components/icon.vue#L267), I believe the animation should be `pulseInfoIns`, not `pulseInfogIns`
2) [This](https://github.com/JorgenVatle/vue-sweetalert-icons/blob/master/src/components/icon.vue#L79) should probably be removed since you're generating prefixes using autoprefixer

Thanks for all your hard work!

**Comment by JorgenVatle** [comment]
Aha! Nice catch, thanks for bringing that up. 👍

I don't believe the project uses autoprefixer, though it probably should.
