### ISSUE TITLE
be able to set the size will be better than

### ISSUE THREAD

**Issue by kane213409** [JorgenVatle/vue-sweetalert-icons#4]
i'm a back-end and i'm not so good at front-end, i have clone the code and trying to change the width, height and etc.., but it's not work, please tell me how can i change the size, thanks!

**Comment by JorgenVatle** [comment]
The icons can unfortunately not be resized with traditional `height` and `width` CSS properties.

You can, however, resize the icons using the CSS [`transform`](https://developer.mozilla.org/en-US/docs/Web/CSS/transform) property.

```vue
<template>
  <sweetalert-icon icon="success" id="my-success-icon" />
</template>

<style>
  #my-success-icon {
    transform: scale(0.5); /* Here we're setting the icon size to 50% of it's original size */
  }
</style>
```
The above example reduces the size of the 'success' icon down to 50%. Use `scale(1.5)` if you want to increase its size by 50%.

Hope this helps! 🙌

**Comment by kane213409** [comment]
it's work, thank you!

**Comment by JorgenVatle** [comment]
Great to hear! 🙌

I'll go ahead and close the issue now. 😊
